/**
 * Type declarations for the floorplan WASM module
 * 
 * These types will be automatically generated by wasm-bindgen when you build,
 * but this file provides the interface for development before building.
 */

declare module 'floorplan-wasm' {
  /**
   * Initialize the WASM module
   * This must be called before using any other functions
   */
  export default function init(): Promise<void>;

  /**
   * Initialize the floorplan system
   * @returns Initialization status message
   */
  export function init_floorplan(): string;

  /**
   * Greet a user (test function)
   * @param name - Name to greet
   * @returns Greeting message
   */
  export function greet(name: string): string;

  // Add more function declarations here as you expose them from Rust
}

/**
 * Extend this interface as you add more functions to the Rust library
 */
export interface FloorplanWasmModule {
  init_floorplan: () => string;
  greet: (name: string) => string;
  
  // Future functions can be added here:
  // generate_floor_plan: (width: number, height: number) => FloorPlan;
  // optimize_layout: (layout: Layout) => Layout;
  // etc.
}
