/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\scene.gltf --transform 
Files: .\scene.gltf [457.9KB] > C:\projects\nosta-heroes\resources\just_a_unicorn\scene-transformed.glb [1.12MB] (-145%)
Author: nottodayrender (https://sketchfab.com/nottodayrender)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/just-a-unicorn-8d0ae2d4b1ac4d1f8ab2adcdcc01cc8f
Title: Just a Unicorn!
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";
import type { GLTF } from "three-stdlib";

type AnimationName = "uprun" | "still" | "run" | "walk";

const animationMap: Record<AnimationName, string> = {
  uprun: "Armature|FinAction(Run&UP)",
  still: "Armature|PoseLib",
  run: "Armature|RUNFIN",
  walk: "Armature|Walking_01",
} as const;

interface UnicornProps {
  animation: AnimationName;
  [key: string]: any;
}

type GLTFResult = GLTF & {
  nodes: {
    _rootJoint: THREE.Bone;
    Object_12: THREE.SkinnedMesh;
    Object_13: THREE.SkinnedMesh;
    Object_15: THREE.SkinnedMesh;
    Object_17: THREE.SkinnedMesh;
    Object_19: THREE.SkinnedMesh;
  };
  materials: {
    Unicorn1: THREE.MeshStandardMaterial;
    down: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    Eyes: THREE.MeshStandardMaterial;
    Hairs1: THREE.MeshStandardMaterial;
  };
};

export function Unicorn(props: UnicornProps) {
  const { animation } = props;
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/scene-transformed.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    const action = actions[animationMap[animation]];
    if (action) {
      action
        .reset()
        .setEffectiveTimeScale(1)
        .setEffectiveWeight(1)
        .fadeIn(0.5)
        .play();
    }
    return () => {
      if (action) {
        action.fadeOut(0.5);
      }
    };
  }, [animation, actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_12"
          geometry={nodes.Object_12.geometry}
          material={materials.Unicorn1}
          skeleton={nodes.Object_12.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_13"
          geometry={nodes.Object_13.geometry}
          material={materials.down}
          skeleton={nodes.Object_13.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_15"
          geometry={nodes.Object_15.geometry}
          material={materials.material}
          skeleton={nodes.Object_15.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_17"
          geometry={nodes.Object_17.geometry}
          material={materials.Eyes}
          skeleton={nodes.Object_17.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name="Object_19"
          geometry={nodes.Object_19.geometry}
          material={materials.Hairs1}
          skeleton={nodes.Object_19.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
